---
title: "Dissertation_code"
author: "Hsuan Meng"
date: "2023-06-12"
output: github_document
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```
```{r packages}
##load packages
library(readxl)
library(dplyr)
library(skimr)
library(zoo)
library(tidyr)
library(GGally)
library(ggplot2)
library(reshape2)
library(corrplot)
library(mclust)
library(factoextra)
library(cluster)
library(dendextend)
library(psych)
```
```{r insert_data}
##insert data
ARDS<-read_xlsx("/Users/meng/Library/Mobile Documents/com~apple~CloudDocs/Desktop/Glasgow/Dissertation/Cluster Analysis of Acute Respiratory Distress Syndrome - PreECMO data/ARDSdata.xlsx")
```

### Explanatory Data Analysis
## Data Preprossing
```{r EDA}
##remove all Day1ECMO variables from the dataset
head(ARDS)
ARDS%>%
  skim()
ARDS<-ARDS[,c(1:8,seq(10,length(ARDS),2))]
ARDS<-ARDS[,-7]
ARDS<-ARDS[,c(5:35)]

##raw data summary
raw<-ARDS%>%
  skim()
sum(raw$n_missing>0)

##encode the variable
ARDS$ECMO_Survival<-ifelse(ARDS$ECMO_Survival=="Y",0,1)
ARDS$Hospital_Survival<-ifelse(ARDS$Hospital_Survival=="Y",0,1)
##remove variable which have more than 50% missing value
ARDS<-ARDS[,-21]

##median imputation
ards_filled <- na.aggregate(ARDS[,3:30], FUN = median)
ards_filled%>%
  skim()

##scale the data
scale<-scale(ards_filled)
ards_new<-cbind(scale,ARDS[,1:2])

##remove outliers
bps<-ards_new[1:28]
bpp <- gather(bps, key = "PreECMO", value = "range")
ggplot(data = bpp, aes(x = PreECMO, y = range)) +
  geom_boxplot()+
  xlab("PreECMO") +
  ylab("value") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))+
  ggtitle("Boxplot of continuous variables")
rows<- rowSums(scale > 5 | scale < -5) == 0
sum(rows=="FALSE")
filtered_data <- subset(ards_new, !apply(scale, 1, function(x) any(x > 5 | x < -5)))

##skewness
skew_values <- sapply(filtered_data[,1:28], skew)

##log transform
### Add a constant offset to make the values positive
x<-filtered_data[,1:28]
offset <- abs(min(x)) + 1 # Add 1 to avoid taking the logarithm of zero
x_offset <- x + offset
### Apply logarithmic transformation
log_data <- log(x_offset)

##combine data
log_data<-cbind(log_data,filtered_data[,29:30])

##pairwise scatterplot
pairs(log_data[,1:10],pch=20, lower.panel=NULL, cex.labels = 1.3, col = c("pink", "lightblue"))
```

## Correlation
```{r correlation}
##correlation between continuous variables
C <- cor(log_data[,1:28])
corrplot(C, type="upper", order="hclust", tl.col="black", tl.srt=45, tl.cex = 0.7)

cor<-round(cor(log_data[,1:28]),2)
max(cor[cor<1])
min(cor)
```

## Dimension Reduction
```{r dimension reduction}
##Principal Component Analysis
ards_pca<-princomp(log_data[,1:28], cor = FALSE) #covariance
summary(ards_pca) #at least 80%, the smallest number of components is 12
pca<-ards_pca$scores[,1:12]
head(pca)
ards_pca$loadings
```


### Classification Analysis
## Hierarchical Analysis
```{r Hierarchical Analysis}
##optima number of cluster for hierarchical cluster
ggplot_hclus <-fviz_nbclust(pca, FUN=hcut, method="silhouette")
ggplot_hclus

##single linkage
ards_hcluss<- hclust(dist(pca), method = "single")
##complete linkage
ards_hclusc<- hclust(dist(pca), method = "complete")
##average linkage
ards_hclusa<- hclust(dist(pca), method = "average")

##cut the tree into 2 clusters
cutsingle<- cutree(ards_hcluss,k=2)
cutcomplete<- cutree(ards_hclusc,k=2)
cutaverage<- cutree(ards_hclusa,k=2)
###hierarchical plot###
par(mfrow=c(1,3),cex=1.2)
plot(silhouette(cutsingle, dist(pca)),
     col=c("lightblue", "pink"),
     main="Silhouette plot of single linkage")
plot(silhouette(cutcomplete,dist(pca)),
     col=c("lightblue", "pink"),
     main="Silhouette plot of complete linkage")
plot(silhouette(cutaverage,dist(pca)),
     col=c("lightblue", "pink"),
     main="Silhouette plot of average linkage")

##built the average linkage tree with 2 clusters
fviz_dend(ards_hclusa, k = 2,
          cex = 0.5,
          k_colors = c("jco"),
          color_labels_by_k = TRUE,
          horiz = TRUE,
          rect = TRUE, rect_fill = TRUE,rect_border = "jco",
          main = "Cluster Dendrogram (Average linkage)")
sum(cutaverage==2)
```


##K-means
```{r K-means}
##optima number of cluster for kmeans
ggplot_kmeans <-fviz_nbclust(pca, FUN=kmeans, method="silhouette")
ggplot_kmeans


set.seed(2023)
ards_km <- kmeans(pca, center=2, nstart = 50)

###kmeans plot###
df <- data.frame(pca, Cluster = factor(ards_km$cluster))
plot(df[,1:5], col=ards_km$cluster+6, pch=16, cex=0.7)


set.seed(2023)
# Initialize variables
max_ari <- -Inf
min_ari <- Inf
max_i <- NULL
min_i <- NULL

for (i in 2:12) {
  compa <- kmeans(pca[, c(1)], center = 2, nstart = 50)
  compb <- kmeans(pca[, c(i)], center = 2, nstart = 50)
  ari <- adjustedRandIndex(compa$cluster, compb$cluster)
  # Check and update maximum and minimum ARI values
  if (ari > max_ari) {
    max_ari <- ari
    max_i <- i
  }
  if (ari < min_ari) {
    min_ari <- ari
    min_i <- i
  }
  cat("Component 1 by", i, "=", ari, "\n")
}
cat("Maximum ARI value:", max_ari, "at component", max_i, "\n")
cat("Minimum ARI value:", min_ari, "at component", min_i, "\n")

#compare two clusters
##contingency tables (1&2)
comp1<- kmeans(pca[, c(1)], center = 2, nstart = 50)
comp2<- kmeans(pca[, c(2)], center = 2, nstart = 50)
addmargins(table(comp1$cluster, comp2$cluster))
ari1_2<-adjustedRandIndex(comp1$cluster, comp2$cluster)
print(ari1_2)

##contingency tables (1&9)
comp9<- kmeans(pca[, c(9)], center = 2, nstart = 50)
addmargins(table(comp1$cluster, comp9$cluster))
ari1_9<-adjustedRandIndex(comp1$cluster, comp9$cluster)
print(ari1_9)

##plot (1&2)
ards_km1_2 <- kmeans(pca[,c(1,2)], center=2, nstart = 50)
plot(pca[,c(1,2)], col=(ards_km$cluster+6), main="K-means result with 2 clusters",
     pch=20, cex=2.5, xlab="Comp.1",ylab="Comp.2", cex.main=1)

##plot (1&9)
ards_km1_9 <- kmeans(pca[,c(1,9)], center=2, nstart = 50)
plot(pca[,c(1,9)], col=(ards_km$cluster+6), main="K-means result with 2 clusters",
     pch=20, cex=2.5, xlab="Comp.1",ylab="Comp.9", cex.main=1)
```

###Fisher's exact test
```{r statistical test}
set.seed(2023)
#kmeans
##hospital(1)
khospital1<-table(comp1$cluster,filtered_data[,30])
khospitalfish1<- fisher.test(khospital1)
print(khospitalfish1)

##hospital(12)
comp12 <- kmeans(pca[, c(1:12)], center = 2, nstart = 50)
khospital12<-table(comp12$cluster,filtered_data[,30])
khospitalfish12<- fisher.test(khospital12)
print(khospitalfish12)

##hospital(entire)
pca28<-ards_pca$scores[,1:28]
comp28 <- kmeans(pca28[, c(1:28)], center = 2, nstart = 50)
khospital28<-table(comp28$cluster,filtered_data[,30])
khospitalfish28<- fisher.test(khospital28)
print(khospitalfish28)
```